"""NCU profiling subprocess runner.

Wraps the pieces needed to drive Nsight Compute against the custom
CUDA kernel we just compiled:

  1. ``locate_ncu_binary()`` / ``ensure_ncu_report_importable()`` —
     discover the ``ncu`` CLI and ``ncu_report`` Python module across
     the various places NVIDIA installs Nsight Compute.

  2. ``build_harness_files()`` — write a self-contained harness.py +
     state.pkl into a temp dir. The harness reuses the backend adapter
     (``backend.load(artifact)`` → ``create_model()`` → forward pass),
     the same mechanism as the main eval pipeline. The precompiled
     ``.so`` is dlopen'd directly via the backend's preloaded-extension
     registry, so no source recompilation occurs and no ``load_inline``
     cflag patching is needed inside the harness.

  3. ``run_ncu()`` — invoke ``ncu --set <set> -k regex:^(...)$ -c 1
     --target-processes all -o report.ncu-rep --force-overwrite python
     harness.py state.pkl``. Translates every failure mode into a single
     ``ncu_warning`` string so the caller can attach it to
     ``metadata.ncu`` without aborting the evaluation.

The ``-lineinfo`` (or other) cflag injection that NCU source-level
metrics require is handled at compile time by
:func:`kernelgym.toolkit.kernelbench.loading.load_custom_model` — see
its ``extra_cuda_cflags`` parameter.

All paths are intentionally subprocess-driven (ncu can't easily attach
to an already-running Python process while torch is mid-eval).
"""

from __future__ import annotations

import logging
import os
import pickle
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional, Tuple

logger = logging.getLogger("kernelgym.toolkit.kernelbench.ncu_runner")


# ---------------------------------------------------------------------------
# Path discovery — Nsight Compute install layout varies across vendors
# ---------------------------------------------------------------------------
def _candidate_nsight_dirs() -> List[Path]:
    cands: List[Path] = []
    for root in ("/usr/local", "/opt/nvidia", "/opt/cuda"):
        p = Path(root)
        if not p.is_dir():
            continue
        for sub in p.glob("cuda-*/nsight-compute-*"):
            if sub.is_dir():
                cands.append(sub)
        for sub in p.glob("nsight-compute-*"):
            if sub.is_dir():
                cands.append(sub)
    return cands


def locate_ncu_binary() -> Optional[str]:
    """Return absolute path to ``ncu`` or None.

    Tries PATH first; falls back to common Nsight Compute install dirs
    and prepends the discovered dir to PATH so child subprocesses inherit it.
    """
    p = shutil.which("ncu")
    if p:
        return p
    for d in _candidate_nsight_dirs():
        ncu = d / "ncu"
        if ncu.is_file() and os.access(ncu, os.X_OK):
            os.environ["PATH"] = f"{d}:{os.environ.get('PATH', '')}"
            logger.info("ncu binary discovered at %s; prepended to PATH", ncu)
            return str(ncu)
    return None


def ensure_ncu_report_importable(extra_paths: Optional[List[str]] = None) -> bool:
    """Try to ``import ncu_report``; return True on success.

    Walks common Nsight Compute install dirs for
    ``extras/python/ncu_report.py`` and prepends to ``sys.path``. Also
    propagates the discovered path to ``PYTHONPATH`` so subprocesses can
    import it.
    """
    try:
        import ncu_report  # noqa: F401
        return True
    except ImportError:
        pass

    candidates: List[Path] = []
    for p in (extra_paths or []):
        candidates.append(Path(p))
    for d in _candidate_nsight_dirs():
        candidates.append(d / "extras" / "python")

    for py in candidates:
        if (py / "ncu_report.py").is_file():
            sys.path.insert(0, str(py))
            try:
                import ncu_report  # noqa: F401
                old = os.environ.get("PYTHONPATH", "")
                if str(py) not in old.split(os.pathsep):
                    os.environ["PYTHONPATH"] = (
                        f"{py}{os.pathsep}{old}" if old else str(py)
                    )
                logger.info("ncu_report imported from %s", py)
                return True
            except ImportError:
                continue
    return False


# ---------------------------------------------------------------------------
# Harness generation
# ---------------------------------------------------------------------------
_HARNESS_TEMPLATE = '''# Auto-generated by kernelgym ncu_runner. DO NOT EDIT BY HAND.
"""NCU profiling harness — runs one forward pass of ModelNew under ncu.

Reuses the backend adapter (``backend.load(artifact)`` →
``create_model()`` → forward pass), exactly like the main eval pipeline.
The precompiled .so is dlopen'd via the backend's preloaded-extension
registry; no source re-exec, no nvcc invocation, no load_inline patch.
"""
from __future__ import annotations

import os
import pickle
import sys
import torch


def _set_seed(seed: int) -> None:
    import random
    random.seed(seed)
    try:
        import numpy as np
        np.random.seed(seed)
    except Exception:
        pass
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: harness.py state.pkl", file=sys.stderr)
        return 2
    with open(sys.argv[1], "rb") as f:
        state = pickle.load(f)

    reference_code: str = state["reference_code"]
    artifact: dict = state["artifact"]
    backend_adapter_name: str = state.get("backend_adapter_name", "kernelbench")
    seed: int = int(state.get("seed", 42))
    warmup_iters: int = int(state.get("warmup_iters", 1))

    if not torch.cuda.is_available():
        print("[harness] CUDA not available; aborting", file=sys.stderr)
        return 3

    device = torch.device("cuda:0")
    torch.cuda.set_device(device)

    # 1. Reference module: gives us get_init_inputs() + get_inputs().
    ref_ns = {"__name__": "stark_ncu_ref"}
    exec(compile(reference_code, "<reference>", "exec"), ref_ns)
    get_init_inputs = ref_ns.get("get_init_inputs")
    get_inputs = ref_ns.get("get_inputs")
    if get_init_inputs is None or get_inputs is None:
        print("[harness] reference_code missing get_init_inputs / get_inputs", file=sys.stderr)
        return 4

    # 2. Load the precompiled model via backend adapter — same path as
    #    _eval_kernel_against_ref_impl. The backend's preloaded-extension
    #    registry intercepts load_inline(name=...) and returns the cached
    #    .so module directly, so cflag alignment is irrelevant here.
    from kernelgym.backend import get_backend

    backend = get_backend(backend_adapter_name)
    handle = backend.load(artifact, device=device, context={})
    session = backend.open_session(handle, device=device)

    try:
        # 3. Build inputs and model exactly like the eval pipeline.
        _set_seed(seed)
        init_inputs = get_init_inputs()
        init_inputs = [
            x.cuda(device=device) if isinstance(x, torch.Tensor) else x
            for x in init_inputs
        ]

        with torch.no_grad():
            _set_seed(seed)
            model = session.create_model(
                init_inputs, no_grad=True, synchronize=True
            )

            _set_seed(seed)
            inputs = get_inputs()
            inputs = [
                x.cuda(device=device) if isinstance(x, torch.Tensor) else x
                for x in inputs
            ]

            torch.cuda.synchronize(device=device)

            # Warmup so caches/launches reach steady state.
            for _ in range(max(0, warmup_iters)):
                model(*inputs)
                torch.cuda.synchronize(device=device)

            # The pass we actually want ncu to record.
            out = model(*inputs)
            torch.cuda.synchronize(device=device)

        print(f"[harness] forward complete; out type={type(out).__name__}")
        return 0
    finally:
        session.close()


if __name__ == "__main__":
    sys.exit(main())
'''


def build_harness_files(
    tmpdir: Path,
    *,
    reference_code: str,
    artifact: dict,
    backend_adapter_name: str = "kernelbench",
    seed: int = 42,
    warmup_iters: int = 1,
) -> Tuple[Path, Path]:
    """Write ``harness.py`` + ``state.pkl`` into ``tmpdir``.

    The harness loads the precompiled model via ``backend.load(artifact)``
    — the same path as the main eval pipeline.  ``artifact`` must carry at
    least ``code``, ``build_dir``, ``entry_point``, ``backend``, and
    ``device`` so the backend adapter can dlopen the cached .so.

    Returns ``(harness_path, state_path)``.
    """
    tmpdir.mkdir(parents=True, exist_ok=True)
    harness_path = tmpdir / "harness.py"
    state_path = tmpdir / "state.pkl"

    harness_path.write_text(_HARNESS_TEMPLATE)
    state = {
        "reference_code": reference_code,
        "artifact": artifact,
        "backend_adapter_name": backend_adapter_name,
        "seed": int(seed),
        "warmup_iters": int(warmup_iters),
    }
    with open(state_path, "wb") as f:
        pickle.dump(state, f, protocol=pickle.HIGHEST_PROTOCOL)
    return harness_path, state_path


# ---------------------------------------------------------------------------
# NCU subprocess driver
# ---------------------------------------------------------------------------
def run_ncu(
    *,
    harness_path: Path,
    state_path: Path,
    report_path: Path,
    kernel_regex: str,
    device_index: int,
    timeout_sec: int = 180,
    ncu_set: str = "full",
    launch_count: int = 1,
    extra_env: Optional[dict] = None,
) -> Tuple[bool, Optional[str], dict]:
    """Run ncu against the harness; return (ok, ncu_warning, details).

    ``details`` carries the raw stdout/stderr tails + return code so
    the caller can plumb them into logs. ``ok=True`` iff the report
    file is non-empty AND ncu's exit code is 0.

    ``launch_count`` is the total number of matching kernel launches
    NCU will profile (passed through ``-c <N>``). NCU counts launches
    across the whole process, not per-kernel name, so when profiling
    N distinct kernels each launched once, this should be at least N.
    """
    details: dict = {
        "cmd": None,
        "returncode": None,
        "stdout_tail": "",
        "stderr_tail": "",
        "report_size_bytes": 0,
    }

    ncu_bin = locate_ncu_binary()
    if not ncu_bin:
        return False, (
            "ncu binary not found on PATH or under common Nsight Compute install paths"
        ), details

    if not kernel_regex:
        return False, "no __global__ kernel names available; skipping ncu", details

    env = os.environ.copy()
    if extra_env:
        env.update(extra_env)
    # Pin the device so ncu profiles the same SM the worker just used.
    env["CUDA_VISIBLE_DEVICES"] = str(device_index)

    cmd = [
        ncu_bin,
        "--set", ncu_set,
        "-k", f"regex:{kernel_regex}",
        "-c", str(max(1, int(launch_count))),
        "--target-processes", "all",
        "-o", str(report_path),
        "--force-overwrite",
        sys.executable, str(harness_path), str(state_path),
    ]
    details["cmd"] = " ".join(cmd)
    logger.info("[ncu] %s", details["cmd"])

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True, text=True,
            env=env,
            timeout=timeout_sec,
        )
    except subprocess.TimeoutExpired as e:
        return False, f"ncu timed out after {e.timeout}s", details
    except FileNotFoundError as e:
        return False, f"ncu binary not executable: {e}", details

    details["returncode"] = proc.returncode
    details["stdout_tail"] = (proc.stdout or "")[-4000:]
    details["stderr_tail"] = (proc.stderr or "")[-4000:]

    combined = (proc.stdout or "") + (proc.stderr or "")

    if "ERR_NVGPUCTRPERM" in combined:
        return False, (
            "ERR_NVGPUCTRPERM: profiling counters restricted to admin. "
            "Run with sudo or set NVreg_RestrictProfilingToAdminUsers=0 "
            "in /etc/modprobe.d/nvidia.conf and reload the driver."
        ), details
    if "could not deploy stock section files" in combined.lower():
        return False, (
            "ncu cannot deploy section files; set HOME to a writable directory."
        ), details

    if proc.returncode != 0:
        return False, (
            f"ncu exited with returncode={proc.returncode}; "
            f"stderr_tail={details['stderr_tail'][:500]}"
        ), details

    if not report_path.is_file():
        return False, "ncu produced no report file", details

    sz = report_path.stat().st_size
    details["report_size_bytes"] = sz
    if sz == 0:
        return False, (
            "ncu produced an empty report file. -k regex may not have "
            "matched any launched kernel, or the harness crashed."
        ), details

    return True, None, details
